### ISSUE TITLE
Melhorias com Bootstrap

### ISSUE THREAD

**Issue by tuliomarcos** [guilhermjosue/Projeto-Bootstrap#1]
Fala man!

Aqui vai uma sugestão de melhoria quando vc ta usando bootstrap no projeto. Percebi que na sua home não esta totalmente responsiva e tem alguns componentes encavalando em outros :/

E o bootstrap foi criado principalmente pra nos ajudar com a responsividade em sites e app, por isso ele tem os grids dele muito bem definidos e estabelecidos. Sugiro que leia depois essas partes da documentação do bootstrap depois pra entender melhor essa parte de layout e grid deles: 

1º: https://getbootstrap.com.br/docs/4.1/layout/overview/
2º: https://getbootstrap.com.br/docs/4.1/layout/grid/

Enfim, sugiro que vc trabalhe mais com os col-xl, col-lg, col-md, col-sm e col xs. Além deles ajudarem muito na questão de resposividade com o posicionamento dos elementos, ele diminui o uso de mediaQueries no seu css, deixando o seu código css mais enxuto e clean :)

Este é um exemplo da onde cada um dos cols que eu citei a cima fazem efeito no seu código:

```
// Dispositivos extra small (telefones em modo retrato, com menos de 576px)
@media (max-width: 575.98px) { ... }

// Dispositivos small (telefones em modo paisagem, com 576px ou mais)
@media (min-width: 576px) and (max-width: 767.98px) { ... }

// Dispositivos médios (tablets com 768px ou mais)
@media (min-width: 768px) and (max-width: 991.98px) { ... }

// Dispositivos large (desktops com 992px ou mais)
@media (min-width: 992px) and (max-width: 1199.98px) { ... }

// Dispositivos extra large (desktops grandes com 1200px ou mais)
@media (min-width: 1200px) { ... }
```

Aqui esta um dos trechos do seu código que vc pode melhorar fazendo bom uso dos "cols" do bootstrap, boa sorte!
 
https://github.com/guilhermjosue/Projeto-Bootstrap/blob/72c5acc90d8e4cf7156d1ca8463c4a43519fea8c/index.html#L125

**Comment by guilhermjosue** [comment]
Olá amigo,
Conforme alguns erros localizados por você, irei fazer as alterações para melhoria da page.
Peço que após da correção retorno com outro feedback.
Obrigado !

**Comment by tuliomarcos** [comment]
Top man! ficou muito bom, acho que você conseguiu pegar a essência do bootstrap e o mais importante dele que são seus "cols". 

Um bom exercício pra você agora é praticar o bootstrap num projeto do dia a dia da nossa aréa. Da um fork no meu repositório landing_page: 
https://github.com/tuliomarcos/landing_page

Lá vão ter 3 landing pages que foi feito pra uma banda que faz eventos de casamento, confraternização, formaturas, etc... ele está com alguns bugs e com responsividade meio bugada com o bootstrap. No caso a versão do bootstrap desses projetos é a 3.7 que é um pouco diferente da mais atual que é a que você aprendeu que é a versão 4.1

A missão é você dar um fork lá no repo e tentar sanar todos os bugs que vc conseguir nos três projetos(apesar deles serem semelhantes, cada um deles tem um bug diferente). Com esse exercício você já pratica um pouco mais de bootstrap e já treina e aumenta a contribuição aqui no gitHub com pullRequests, boa sorte! :)

**Comment by guilhermjosue** [comment]
Valeu Brother !
Vou encarar esse desafio de frente e tentar resolver todos os problemas.
Valeu pela confiança.
